#
# This file contains configuration flags to customize your site
#

# The name of your site (displayed in the header)
name: Sujin Karunakaran

# A short bio or description (displayed in the header)
description: A person in a world

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://barryclark.co

# A URL pointing to your avatar or profile pic
# To use your Gravatar: (the one that GitHub uses for your profile pic)
#   1. Go to https://github.com/YOURUSERNAME/
#   2. Right click and Copy Image URL on your profile pic,
#   3. Take the first long ID from the URL and paste it in place of mine below
avatar: https://s.redditmedia.com/t5_7oxpl/styles/communityIcon_dd4xeohq6y401.jpg?fit=crop&crop=faces%2Centropy&arh=1.0&w=256&h=256&s=0fd5415ca9099acefabf69f56fefc94c

# Your disqus username, entering this will enable commenting on posts
disqus: barryclark

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-2530088-4

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: barryclark
  instagram: 
  linkedin: bazclark
  pinterest: 
  rss: 
  twitter: baznyc

#
# !! You don't need to change any of the configuration flags below !!
#

baseurl: ""
markdown: kramdown
highlighter: pygments
permalink: /:title

# Emoji please!
gems:
  - jemoji

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - scss
    - README.md
